version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    networks:
      - main

  backend:
    container_name: backend
    image: backend:dev
    build: 
      context: ./backend
      dockerfile: scripts/dev/Dockerfile
    command: "scripts/dev/start_dev.sh"
    volumes:
      - ./backend:/code
      - django-static:/code/static
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - main
    depends_on: 
      - postgres

volumes:
  pg-data:
  django-static:

networks:
  main:
    driver: bridge